
[functions.replicate-call]
enabled = true
verify_jwt = true
import_map = "./functions/replicate-call/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/replicate-call/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/replicate-call/*.html" ]

[auth]
enabled = true

site_url = "http://localhost:3000"
additional_redirect_urls = []
 jwt_expiry = 3600
 enable_refresh_token_rotation = true
 refresh_token_reuse_interval = 10
 [auth.email]
 enable_signup = true
 double_confirm_changes = true
enable_confirmations = true
 secure_password_change = false
max_frequency = "1m0s"
 otp_length = 6
 otp_expiry = 3600
 [auth.email.template]